// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/issues/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/issues/[id].patch').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/issues/[id].put').default>>>>
    }
    '/api/issues': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/issues/index').default>>>>
    }
    '/api/pages/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/[id].put').default>>>>
    }
    '/api/pages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/index.post').default>>>>
    }
    '/api/projects/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]').default>>>>
    }
    '/api/projects/:id/columns': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/columns').default>>>>
    }
    '/api/projects/:id/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/pages.get').default>>>>
    }
    '/api/projects/:id/sprints/:sprintId/burndown': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/sprints/[sprintId]/burndown').default>>>>
    }
    '/api/projects/:id/sprints': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[id]/sprints/index').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index').default>>>>
    }
    '/api/sprints/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sprints/[id].patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}