// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/7/2026, 4:52:00 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Desktop/JIRA-REN/JIRA-REN/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/plugins/**/*.{js,ts,mjs}","D:/Desktop/JIRA-REN/JIRA-REN/client/composables/**/*.{js,ts,mjs}","D:/Desktop/JIRA-REN/JIRA-REN/client/utils/**/*.{js,ts,mjs}","D:/Desktop/JIRA-REN/JIRA-REN/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/JIRA-REN/JIRA-REN/client/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;